Rails.application.routes.draw do
  match('/', {:via => :get, :to => 'tags#list'})
  # match('/', {:via => :get, :to => 'users#read'})
  # match('users', {:via => :get, :to => 'users#read'})
  # match('users', {:via => :post, :to => 'users#create'})
  # match('users/new', {:via => :get, :to => 'users#new'})
  # match('users/all', {:via => :get, :to => 'users#list'})
  # match('users/:id/edit', {:via => :get, :to => 'users#get'})
  # match('users/:id', {:via => :patch, :to => 'users#update'})
  # match('users/:id', {:via => :delete, :to => 'users#destroy'})
  # match('recipes', {:via => :get, :to => 'recipes#new'})
  # match('recipes', {:via => :post, :to => 'recipes#create'})
  # match('recipes/all', {:via => :get, :to => 'recipes#list'})
  # match('recipes/:id/read', {:via => :get, :to => 'recipes#read'})
  # match('recipes/:id/edit', {:via => :get, :to => 'recipes#edit'})
  # match('recipes/:id', {:via => :patch, :to => 'recipes#update'})
  # match('recipes/:id', {:via => :delete, :to => 'recipes#destroy'})
  match('tags', {:via => :get, :to => 'tags#list'})
  match('tags', {:via => :post, :to => 'tags#create'})
  match('tags/new', {:via => :get, :to => 'tags#new'})
  match('tags/:id/edit', {:via => :get, :to => 'tags#edit'})
  match('tags/:id', {:via => :patch, :to => 'tags#update'})
  match('tags/:id', {:via => :delete, :to => 'tags#destroy'})
end
